export * from './user.repository';
export * from './list.repository';
export * from './list-movie.repository';
export * from './list-serie.repository';
export * from './movie.repository';
export * from './serie.repository';
export * from './actor.repository';
export * from './movie-actor.repository';
export * from './serie-actor.repository';
